apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: prod-devtrails-crt
spec:
  secretName: prod-devtrails-crt-secret
  dnsNames:
  - prod.devtrails.co.nz
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - prod.devtrails.co.nz
  issuerRef:
    name: letsencrypt-prod
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
